version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    command: [ --auth ]
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    depends_on:
      - mongo-express
    volumes:
      - db_mongo:/data/mongo
    networks:
      - container_network

  mongo-express:
    image: mongo-express
    container_name: express
    restart: always
    ports:
      - 8081:8081
    networks:
      - container_network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$EXPRESS_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$EXPRESS_PASSWORD
      - ME_CONFIG_MONGODB_URL='mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo:27017/'

networks:
  container_network:
    driver: bridge

volumes:
  db_mongo: